Divu
abdo1819/arch_lab09 pull request #9
Opened 2019-10-12 08:54 UTC by HMS-ELKHOLY

- there was ignored files(divufile.sv , spreg.sv) and i added them  despite they are .sv ! ....can anyone tell me how git ignores sv files that are not in .gitignore !

- spregfile for low and high will be edited and i 'll put move from/to hi/lo  instructions at end of the day :saleh will do the same thing and we will merge thogether

2019-10-12 11:34 UTC, abdo1819 requested changes

2019-10-12 11:34 UTC, abdo1819 commented on testbench.sv
> +            end else if (dataadr !== 84) begin
this test bench is used for original instractions from the book create another one for ur instractions

2019-10-12 11:34 UTC, abdo1819 commented on aludec.sv
> +                output logic [3:0] alucontrol,output logic spregwrite );
use indentation for better looking code

2019-10-12 11:34 UTC, abdo1819 commented on aludec.sv
> +
don't add style changes for easier review and minimize conflict solving

2019-10-12 11:34 UTC, abdo1819 commented on aludec.sv
> +
don't add style changes for easier review and minimize conflict solving

2019-10-12 11:34 UTC, abdo1819 commented on divu.asm
> +divu $t2 $t1
you may comment the result after every line and its machine code as in [here](https://github.com/abdo1819/arch_lab09/blob/master/mipstest.asm)

2019-10-12 11:34 UTC, abdo1819 commented on imem.sv
> +    $readmemh("divu.dat", RAM);
leave reading to original hex file memfile__.dat so master allways test original code
* it was a mistake to accept this change

2019-10-12 11:34 UTC, abdo1819 commented on mips.sv
> +module mips(input logic clk,input reset,
and i wonder what does `input` stand for ?
reset is already a logic input

2019-10-12 13:25 UTC, HMS-ELKHOLY commented on testbench.sv
> +            end else if (dataadr !== 84) begin
just for running code ......divu to be tested we need implemnet other extra  instructions not in the task kist ....it will be implmented at end of the day ISA

2019-10-12 13:29 UTC, HMS-ELKHOLY commented on mips.sv
> +module mips(input logic clk,input reset,
mahmoud played alot not my fault here ....will be fixed

2019-10-12 13:32 UTC, HMS-ELKHOLY commented on testbench.sv
> +            end else if (dataadr !== 84) begin
just run code and see that original code works and your code  .....and for divu look at simulation results or wait for the end of the day ....making instruction that need other 2 instructions to be tested is long process..
i don't want  to integrate other changes   done will making extra work ...this is extra for extra

2019-10-14 08:01 UTC, abdo1819 commented on divu.asm
> +divu $t2 $t1
Add this later

2019-10-14 08:01 UTC, abdo1819 commented on imem.sv
> +    $readmemh("divu.dat", RAM);
Will edit this no problem

2019-10-14 08:26 UTC, merged